Search.appendIndex(
    [
                {
            "fqsen": "\\App\\Controller\\CartContoller",
            "name": "CartContoller",
            "summary": "",
            "url": "classes/App-Controller-CartContoller.html"
        },                {
            "fqsen": "\\App\\Controller\\CartContoller\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/App-Controller-CartContoller.html#method_index"
        },                {
            "fqsen": "\\App\\Controller\\CartContoller\u003A\u003AaddItem\u0028\u0029",
            "name": "addItem",
            "summary": "",
            "url": "classes/App-Controller-CartContoller.html#method_addItem"
        },                {
            "fqsen": "\\App\\Controller\\HomeController",
            "name": "HomeController",
            "summary": "",
            "url": "classes/App-Controller-HomeController.html"
        },                {
            "fqsen": "\\App\\Controller\\HomeController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Das\u0020ist\u0020ein\u0020Test",
            "url": "classes/App-Controller-HomeController.html#method_index"
        },                {
            "fqsen": "\\App\\Controller\\HomeController\u003A\u003Agerichte\u0028\u0029",
            "name": "gerichte",
            "summary": "",
            "url": "classes/App-Controller-HomeController.html#method_gerichte"
        },                {
            "fqsen": "\\App\\Entity\\Bestellung",
            "name": "Bestellung",
            "summary": "",
            "url": "classes/App-Entity-Bestellung.html"
        },                {
            "fqsen": "\\App\\Entity\\Bestellung\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Entity-Bestellung.html#method___construct"
        },                {
            "fqsen": "\\App\\Entity\\Bestellung\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Entity-Bestellung.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\Bestellung\u003A\u003AgetGastName\u0028\u0029",
            "name": "getGastName",
            "summary": "",
            "url": "classes/App-Entity-Bestellung.html#method_getGastName"
        },                {
            "fqsen": "\\App\\Entity\\Bestellung\u003A\u003AsetGastName\u0028\u0029",
            "name": "setGastName",
            "summary": "",
            "url": "classes/App-Entity-Bestellung.html#method_setGastName"
        },                {
            "fqsen": "\\App\\Entity\\Bestellung\u003A\u003AgetGerichtVariation\u0028\u0029",
            "name": "getGerichtVariation",
            "summary": "",
            "url": "classes/App-Entity-Bestellung.html#method_getGerichtVariation"
        },                {
            "fqsen": "\\App\\Entity\\Bestellung\u003A\u003AaddGerichtVariation\u0028\u0029",
            "name": "addGerichtVariation",
            "summary": "",
            "url": "classes/App-Entity-Bestellung.html#method_addGerichtVariation"
        },                {
            "fqsen": "\\App\\Entity\\Bestellung\u003A\u003AremoveGerichtVariation\u0028\u0029",
            "name": "removeGerichtVariation",
            "summary": "",
            "url": "classes/App-Entity-Bestellung.html#method_removeGerichtVariation"
        },                {
            "fqsen": "\\App\\Entity\\Bestellung\u003A\u003AgetSammelBestellung\u0028\u0029",
            "name": "getSammelBestellung",
            "summary": "",
            "url": "classes/App-Entity-Bestellung.html#method_getSammelBestellung"
        },                {
            "fqsen": "\\App\\Entity\\Bestellung\u003A\u003AsetSammelBestellung\u0028\u0029",
            "name": "setSammelBestellung",
            "summary": "",
            "url": "classes/App-Entity-Bestellung.html#method_setSammelBestellung"
        },                {
            "fqsen": "\\App\\Entity\\Bestellung\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-Bestellung.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\Bestellung\u003A\u003A\u0024GastName",
            "name": "GastName",
            "summary": "",
            "url": "classes/App-Entity-Bestellung.html#property_GastName"
        },                {
            "fqsen": "\\App\\Entity\\Bestellung\u003A\u003A\u0024GerichtVariation",
            "name": "GerichtVariation",
            "summary": "",
            "url": "classes/App-Entity-Bestellung.html#property_GerichtVariation"
        },                {
            "fqsen": "\\App\\Entity\\Bestellung\u003A\u003A\u0024sammelBestellung",
            "name": "sammelBestellung",
            "summary": "",
            "url": "classes/App-Entity-Bestellung.html#property_sammelBestellung"
        },                {
            "fqsen": "\\App\\Entity\\Gericht",
            "name": "Gericht",
            "summary": "",
            "url": "classes/App-Entity-Gericht.html"
        },                {
            "fqsen": "\\App\\Entity\\Gericht\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Entity-Gericht.html#method___construct"
        },                {
            "fqsen": "\\App\\Entity\\Gericht\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Entity-Gericht.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\Gericht\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "",
            "url": "classes/App-Entity-Gericht.html#method_getName"
        },                {
            "fqsen": "\\App\\Entity\\Gericht\u003A\u003AsetName\u0028\u0029",
            "name": "setName",
            "summary": "",
            "url": "classes/App-Entity-Gericht.html#method_setName"
        },                {
            "fqsen": "\\App\\Entity\\Gericht\u003A\u003AgetNummer\u0028\u0029",
            "name": "getNummer",
            "summary": "",
            "url": "classes/App-Entity-Gericht.html#method_getNummer"
        },                {
            "fqsen": "\\App\\Entity\\Gericht\u003A\u003AsetNummer\u0028\u0029",
            "name": "setNummer",
            "summary": "",
            "url": "classes/App-Entity-Gericht.html#method_setNummer"
        },                {
            "fqsen": "\\App\\Entity\\Gericht\u003A\u003AgetBeschreibung\u0028\u0029",
            "name": "getBeschreibung",
            "summary": "",
            "url": "classes/App-Entity-Gericht.html#method_getBeschreibung"
        },                {
            "fqsen": "\\App\\Entity\\Gericht\u003A\u003AsetBeschreibung\u0028\u0029",
            "name": "setBeschreibung",
            "summary": "",
            "url": "classes/App-Entity-Gericht.html#method_setBeschreibung"
        },                {
            "fqsen": "\\App\\Entity\\Gericht\u003A\u003AgetRestaurant\u0028\u0029",
            "name": "getRestaurant",
            "summary": "",
            "url": "classes/App-Entity-Gericht.html#method_getRestaurant"
        },                {
            "fqsen": "\\App\\Entity\\Gericht\u003A\u003AsetRestaurant\u0028\u0029",
            "name": "setRestaurant",
            "summary": "",
            "url": "classes/App-Entity-Gericht.html#method_setRestaurant"
        },                {
            "fqsen": "\\App\\Entity\\Gericht\u003A\u003AgetKategorie\u0028\u0029",
            "name": "getKategorie",
            "summary": "",
            "url": "classes/App-Entity-Gericht.html#method_getKategorie"
        },                {
            "fqsen": "\\App\\Entity\\Gericht\u003A\u003AsetKategorie\u0028\u0029",
            "name": "setKategorie",
            "summary": "",
            "url": "classes/App-Entity-Gericht.html#method_setKategorie"
        },                {
            "fqsen": "\\App\\Entity\\Gericht\u003A\u003AgetGerichtVariationen\u0028\u0029",
            "name": "getGerichtVariationen",
            "summary": "",
            "url": "classes/App-Entity-Gericht.html#method_getGerichtVariationen"
        },                {
            "fqsen": "\\App\\Entity\\Gericht\u003A\u003AaddGerichtVariationen\u0028\u0029",
            "name": "addGerichtVariationen",
            "summary": "",
            "url": "classes/App-Entity-Gericht.html#method_addGerichtVariationen"
        },                {
            "fqsen": "\\App\\Entity\\Gericht\u003A\u003AremoveGerichtVariationen\u0028\u0029",
            "name": "removeGerichtVariationen",
            "summary": "",
            "url": "classes/App-Entity-Gericht.html#method_removeGerichtVariationen"
        },                {
            "fqsen": "\\App\\Entity\\Gericht\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-Gericht.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\Gericht\u003A\u003A\u0024Name",
            "name": "Name",
            "summary": "",
            "url": "classes/App-Entity-Gericht.html#property_Name"
        },                {
            "fqsen": "\\App\\Entity\\Gericht\u003A\u003A\u0024Nummer",
            "name": "Nummer",
            "summary": "",
            "url": "classes/App-Entity-Gericht.html#property_Nummer"
        },                {
            "fqsen": "\\App\\Entity\\Gericht\u003A\u003A\u0024Beschreibung",
            "name": "Beschreibung",
            "summary": "",
            "url": "classes/App-Entity-Gericht.html#property_Beschreibung"
        },                {
            "fqsen": "\\App\\Entity\\Gericht\u003A\u003A\u0024Restaurant",
            "name": "Restaurant",
            "summary": "",
            "url": "classes/App-Entity-Gericht.html#property_Restaurant"
        },                {
            "fqsen": "\\App\\Entity\\Gericht\u003A\u003A\u0024Kategorie",
            "name": "Kategorie",
            "summary": "",
            "url": "classes/App-Entity-Gericht.html#property_Kategorie"
        },                {
            "fqsen": "\\App\\Entity\\Gericht\u003A\u003A\u0024GerichtVariationen",
            "name": "GerichtVariationen",
            "summary": "",
            "url": "classes/App-Entity-Gericht.html#property_GerichtVariationen"
        },                {
            "fqsen": "\\App\\Entity\\GerichtVariation",
            "name": "GerichtVariation",
            "summary": "",
            "url": "classes/App-Entity-GerichtVariation.html"
        },                {
            "fqsen": "\\App\\Entity\\GerichtVariation\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Entity-GerichtVariation.html#method___construct"
        },                {
            "fqsen": "\\App\\Entity\\GerichtVariation\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Entity-GerichtVariation.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\GerichtVariation\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "",
            "url": "classes/App-Entity-GerichtVariation.html#method_getName"
        },                {
            "fqsen": "\\App\\Entity\\GerichtVariation\u003A\u003AsetName\u0028\u0029",
            "name": "setName",
            "summary": "",
            "url": "classes/App-Entity-GerichtVariation.html#method_setName"
        },                {
            "fqsen": "\\App\\Entity\\GerichtVariation\u003A\u003AgetIsDefault\u0028\u0029",
            "name": "getIsDefault",
            "summary": "",
            "url": "classes/App-Entity-GerichtVariation.html#method_getIsDefault"
        },                {
            "fqsen": "\\App\\Entity\\GerichtVariation\u003A\u003AsetIsDefault\u0028\u0029",
            "name": "setIsDefault",
            "summary": "",
            "url": "classes/App-Entity-GerichtVariation.html#method_setIsDefault"
        },                {
            "fqsen": "\\App\\Entity\\GerichtVariation\u003A\u003AgetPreis\u0028\u0029",
            "name": "getPreis",
            "summary": "",
            "url": "classes/App-Entity-GerichtVariation.html#method_getPreis"
        },                {
            "fqsen": "\\App\\Entity\\GerichtVariation\u003A\u003AsetPreis\u0028\u0029",
            "name": "setPreis",
            "summary": "",
            "url": "classes/App-Entity-GerichtVariation.html#method_setPreis"
        },                {
            "fqsen": "\\App\\Entity\\GerichtVariation\u003A\u003AgetGericht\u0028\u0029",
            "name": "getGericht",
            "summary": "",
            "url": "classes/App-Entity-GerichtVariation.html#method_getGericht"
        },                {
            "fqsen": "\\App\\Entity\\GerichtVariation\u003A\u003AsetGericht\u0028\u0029",
            "name": "setGericht",
            "summary": "",
            "url": "classes/App-Entity-GerichtVariation.html#method_setGericht"
        },                {
            "fqsen": "\\App\\Entity\\GerichtVariation\u003A\u003AgetBestellungen\u0028\u0029",
            "name": "getBestellungen",
            "summary": "",
            "url": "classes/App-Entity-GerichtVariation.html#method_getBestellungen"
        },                {
            "fqsen": "\\App\\Entity\\GerichtVariation\u003A\u003AaddBestellungen\u0028\u0029",
            "name": "addBestellungen",
            "summary": "",
            "url": "classes/App-Entity-GerichtVariation.html#method_addBestellungen"
        },                {
            "fqsen": "\\App\\Entity\\GerichtVariation\u003A\u003AremoveBestellungen\u0028\u0029",
            "name": "removeBestellungen",
            "summary": "",
            "url": "classes/App-Entity-GerichtVariation.html#method_removeBestellungen"
        },                {
            "fqsen": "\\App\\Entity\\GerichtVariation\u003A\u003AgetGeloescht\u0028\u0029",
            "name": "getGeloescht",
            "summary": "",
            "url": "classes/App-Entity-GerichtVariation.html#method_getGeloescht"
        },                {
            "fqsen": "\\App\\Entity\\GerichtVariation\u003A\u003AsetGeloescht\u0028\u0029",
            "name": "setGeloescht",
            "summary": "",
            "url": "classes/App-Entity-GerichtVariation.html#method_setGeloescht"
        },                {
            "fqsen": "\\App\\Entity\\GerichtVariation\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-GerichtVariation.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\GerichtVariation\u003A\u003A\u0024Name",
            "name": "Name",
            "summary": "",
            "url": "classes/App-Entity-GerichtVariation.html#property_Name"
        },                {
            "fqsen": "\\App\\Entity\\GerichtVariation\u003A\u003A\u0024isDefault",
            "name": "isDefault",
            "summary": "",
            "url": "classes/App-Entity-GerichtVariation.html#property_isDefault"
        },                {
            "fqsen": "\\App\\Entity\\GerichtVariation\u003A\u003A\u0024Preis",
            "name": "Preis",
            "summary": "",
            "url": "classes/App-Entity-GerichtVariation.html#property_Preis"
        },                {
            "fqsen": "\\App\\Entity\\GerichtVariation\u003A\u003A\u0024gericht",
            "name": "gericht",
            "summary": "",
            "url": "classes/App-Entity-GerichtVariation.html#property_gericht"
        },                {
            "fqsen": "\\App\\Entity\\GerichtVariation\u003A\u003A\u0024Bestellungen",
            "name": "Bestellungen",
            "summary": "",
            "url": "classes/App-Entity-GerichtVariation.html#property_Bestellungen"
        },                {
            "fqsen": "\\App\\Entity\\GerichtVariation\u003A\u003A\u0024geloescht",
            "name": "geloescht",
            "summary": "",
            "url": "classes/App-Entity-GerichtVariation.html#property_geloescht"
        },                {
            "fqsen": "\\App\\Entity\\Kategorie",
            "name": "Kategorie",
            "summary": "",
            "url": "classes/App-Entity-Kategorie.html"
        },                {
            "fqsen": "\\App\\Entity\\Kategorie\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Entity-Kategorie.html#method___construct"
        },                {
            "fqsen": "\\App\\Entity\\Kategorie\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Entity-Kategorie.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\Kategorie\u003A\u003AgetBezeichner\u0028\u0029",
            "name": "getBezeichner",
            "summary": "",
            "url": "classes/App-Entity-Kategorie.html#method_getBezeichner"
        },                {
            "fqsen": "\\App\\Entity\\Kategorie\u003A\u003AsetBezeichner\u0028\u0029",
            "name": "setBezeichner",
            "summary": "",
            "url": "classes/App-Entity-Kategorie.html#method_setBezeichner"
        },                {
            "fqsen": "\\App\\Entity\\Kategorie\u003A\u003AgetGerichte\u0028\u0029",
            "name": "getGerichte",
            "summary": "",
            "url": "classes/App-Entity-Kategorie.html#method_getGerichte"
        },                {
            "fqsen": "\\App\\Entity\\Kategorie\u003A\u003AaddGericht\u0028\u0029",
            "name": "addGericht",
            "summary": "",
            "url": "classes/App-Entity-Kategorie.html#method_addGericht"
        },                {
            "fqsen": "\\App\\Entity\\Kategorie\u003A\u003AremoveGericht\u0028\u0029",
            "name": "removeGericht",
            "summary": "",
            "url": "classes/App-Entity-Kategorie.html#method_removeGericht"
        },                {
            "fqsen": "\\App\\Entity\\Kategorie\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-Kategorie.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\Kategorie\u003A\u003A\u0024Bezeichner",
            "name": "Bezeichner",
            "summary": "",
            "url": "classes/App-Entity-Kategorie.html#property_Bezeichner"
        },                {
            "fqsen": "\\App\\Entity\\Kategorie\u003A\u003A\u0024Gerichte",
            "name": "Gerichte",
            "summary": "",
            "url": "classes/App-Entity-Kategorie.html#property_Gerichte"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant",
            "name": "Restaurant",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#method___construct"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#method_getName"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003AsetName\u0028\u0029",
            "name": "setName",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#method_setName"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003AgetTelefonNr\u0028\u0029",
            "name": "getTelefonNr",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#method_getTelefonNr"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003AsetTelefonNr\u0028\u0029",
            "name": "setTelefonNr",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#method_setTelefonNr"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003AgetMobil\u0028\u0029",
            "name": "getMobil",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#method_getMobil"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003AsetMobil\u0028\u0029",
            "name": "setMobil",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#method_setMobil"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003AgetStra\u00DFe\u0028\u0029",
            "name": "getStra\u00DFe",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#method_getStra%C3%9Fe"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003AsetStra\u00DFe\u0028\u0029",
            "name": "setStra\u00DFe",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#method_setStra%C3%9Fe"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003AgetHausNr\u0028\u0029",
            "name": "getHausNr",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#method_getHausNr"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003AsetHausNr\u0028\u0029",
            "name": "setHausNr",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#method_setHausNr"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003AgetOeffnungszeit\u0028\u0029",
            "name": "getOeffnungszeit",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#method_getOeffnungszeit"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003AsetOeffnungszeit\u0028\u0029",
            "name": "setOeffnungszeit",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#method_setOeffnungszeit"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003AgetGerichte\u0028\u0029",
            "name": "getGerichte",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#method_getGerichte"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003AaddGerichte\u0028\u0029",
            "name": "addGerichte",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#method_addGerichte"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003AremoveGerichte\u0028\u0029",
            "name": "removeGerichte",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#method_removeGerichte"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003AgetSammelBestellungen\u0028\u0029",
            "name": "getSammelBestellungen",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#method_getSammelBestellungen"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003AaddSammelBestellungen\u0028\u0029",
            "name": "addSammelBestellungen",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#method_addSammelBestellungen"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003AremoveSammelBestellungen\u0028\u0029",
            "name": "removeSammelBestellungen",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#method_removeSammelBestellungen"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003AgetOrt\u0028\u0029",
            "name": "getOrt",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#method_getOrt"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003AsetOrt\u0028\u0029",
            "name": "setOrt",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#method_setOrt"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003A\u0024Name",
            "name": "Name",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#property_Name"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003A\u0024TelefonNr",
            "name": "TelefonNr",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#property_TelefonNr"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003A\u0024Mobil",
            "name": "Mobil",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#property_Mobil"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003A\u0024Stra\u00DFe",
            "name": "Stra\u00DFe",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#property_Stra%C3%9Fe"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003A\u0024HausNr",
            "name": "HausNr",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#property_HausNr"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003A\u0024Oeffnungszeit",
            "name": "Oeffnungszeit",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#property_Oeffnungszeit"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003A\u0024Gerichte",
            "name": "Gerichte",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#property_Gerichte"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003A\u0024SammelBestellungen",
            "name": "SammelBestellungen",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#property_SammelBestellungen"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003A\u0024Ort",
            "name": "Ort",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#property_Ort"
        },                {
            "fqsen": "\\App\\Entity\\SammelBestellung",
            "name": "SammelBestellung",
            "summary": "",
            "url": "classes/App-Entity-SammelBestellung.html"
        },                {
            "fqsen": "\\App\\Entity\\SammelBestellung\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Entity-SammelBestellung.html#method___construct"
        },                {
            "fqsen": "\\App\\Entity\\SammelBestellung\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Entity-SammelBestellung.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\SammelBestellung\u003A\u003AgetAdminURL\u0028\u0029",
            "name": "getAdminURL",
            "summary": "",
            "url": "classes/App-Entity-SammelBestellung.html#method_getAdminURL"
        },                {
            "fqsen": "\\App\\Entity\\SammelBestellung\u003A\u003AsetAdminURL\u0028\u0029",
            "name": "setAdminURL",
            "summary": "",
            "url": "classes/App-Entity-SammelBestellung.html#method_setAdminURL"
        },                {
            "fqsen": "\\App\\Entity\\SammelBestellung\u003A\u003AgetPublicURL\u0028\u0029",
            "name": "getPublicURL",
            "summary": "",
            "url": "classes/App-Entity-SammelBestellung.html#method_getPublicURL"
        },                {
            "fqsen": "\\App\\Entity\\SammelBestellung\u003A\u003AsetPublicURL\u0028\u0029",
            "name": "setPublicURL",
            "summary": "",
            "url": "classes/App-Entity-SammelBestellung.html#method_setPublicURL"
        },                {
            "fqsen": "\\App\\Entity\\SammelBestellung\u003A\u003AgetRestaurant\u0028\u0029",
            "name": "getRestaurant",
            "summary": "",
            "url": "classes/App-Entity-SammelBestellung.html#method_getRestaurant"
        },                {
            "fqsen": "\\App\\Entity\\SammelBestellung\u003A\u003AsetRestaurant\u0028\u0029",
            "name": "setRestaurant",
            "summary": "",
            "url": "classes/App-Entity-SammelBestellung.html#method_setRestaurant"
        },                {
            "fqsen": "\\App\\Entity\\SammelBestellung\u003A\u003AgetBestellung\u0028\u0029",
            "name": "getBestellung",
            "summary": "",
            "url": "classes/App-Entity-SammelBestellung.html#method_getBestellung"
        },                {
            "fqsen": "\\App\\Entity\\SammelBestellung\u003A\u003AaddBestellung\u0028\u0029",
            "name": "addBestellung",
            "summary": "",
            "url": "classes/App-Entity-SammelBestellung.html#method_addBestellung"
        },                {
            "fqsen": "\\App\\Entity\\SammelBestellung\u003A\u003AremoveBestellung\u0028\u0029",
            "name": "removeBestellung",
            "summary": "",
            "url": "classes/App-Entity-SammelBestellung.html#method_removeBestellung"
        },                {
            "fqsen": "\\App\\Entity\\SammelBestellung\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-SammelBestellung.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\SammelBestellung\u003A\u003A\u0024AdminURL",
            "name": "AdminURL",
            "summary": "",
            "url": "classes/App-Entity-SammelBestellung.html#property_AdminURL"
        },                {
            "fqsen": "\\App\\Entity\\SammelBestellung\u003A\u003A\u0024PublicURL",
            "name": "PublicURL",
            "summary": "",
            "url": "classes/App-Entity-SammelBestellung.html#property_PublicURL"
        },                {
            "fqsen": "\\App\\Entity\\SammelBestellung\u003A\u003A\u0024Restaurant",
            "name": "Restaurant",
            "summary": "",
            "url": "classes/App-Entity-SammelBestellung.html#property_Restaurant"
        },                {
            "fqsen": "\\App\\Entity\\SammelBestellung\u003A\u003A\u0024Bestellung",
            "name": "Bestellung",
            "summary": "",
            "url": "classes/App-Entity-SammelBestellung.html#property_Bestellung"
        },                {
            "fqsen": "\\App\\Kernel",
            "name": "Kernel",
            "summary": "",
            "url": "classes/App-Kernel.html"
        },                {
            "fqsen": "\\App\\Kernel\u003A\u003AconfigureContainer\u0028\u0029",
            "name": "configureContainer",
            "summary": "",
            "url": "classes/App-Kernel.html#method_configureContainer"
        },                {
            "fqsen": "\\App\\Kernel\u003A\u003AconfigureRoutes\u0028\u0029",
            "name": "configureRoutes",
            "summary": "",
            "url": "classes/App-Kernel.html#method_configureRoutes"
        },                {
            "fqsen": "\\App\\Repository\\BestellungRepository",
            "name": "BestellungRepository",
            "summary": "",
            "url": "classes/App-Repository-BestellungRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\BestellungRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Repository-BestellungRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\GerichtRepository",
            "name": "GerichtRepository",
            "summary": "",
            "url": "classes/App-Repository-GerichtRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\GerichtRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Repository-GerichtRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\GerichtVariationRepository",
            "name": "GerichtVariationRepository",
            "summary": "",
            "url": "classes/App-Repository-GerichtVariationRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\GerichtVariationRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Repository-GerichtVariationRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\KategorieRepository",
            "name": "KategorieRepository",
            "summary": "",
            "url": "classes/App-Repository-KategorieRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\KategorieRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Repository-KategorieRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\RestaurantRepository",
            "name": "RestaurantRepository",
            "summary": "",
            "url": "classes/App-Repository-RestaurantRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\RestaurantRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Repository-RestaurantRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\SammelBestellungRepository",
            "name": "SammelBestellungRepository",
            "summary": "",
            "url": "classes/App-Repository-SammelBestellungRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\SammelBestellungRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Repository-SammelBestellungRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Controller\\OrderCollectionController",
            "name": "OrderCollectionController",
            "summary": "",
            "url": "classes/App-Controller-OrderCollectionController.html"
        },                {
            "fqsen": "\\App\\Controller\\OrderCollectionController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Das\u0020ist\u0020ein\u0020Test",
            "url": "classes/App-Controller-OrderCollectionController.html#method_index"
        },                {
            "fqsen": "\\App\\Controller\\OrderCollectionController\u003A\u003Anew\u0028\u0029",
            "name": "new",
            "summary": "",
            "url": "classes/App-Controller-OrderCollectionController.html#method_new"
        },                {
            "fqsen": "\\App\\Controller\\OrderCollectionController\u003A\u003AadminView\u0028\u0029",
            "name": "adminView",
            "summary": "",
            "url": "classes/App-Controller-OrderCollectionController.html#method_adminView"
        },                {
            "fqsen": "\\App\\Controller\\OrderCollectionController\u003A\u003AsetSessionParam\u0028\u0029",
            "name": "setSessionParam",
            "summary": "",
            "url": "classes/App-Controller-OrderCollectionController.html#method_setSessionParam"
        },                {
            "fqsen": "\\App\\Entity\\Ort",
            "name": "Ort",
            "summary": "",
            "url": "classes/App-Entity-Ort.html"
        },                {
            "fqsen": "\\App\\Entity\\Ort\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Entity-Ort.html#method___construct"
        },                {
            "fqsen": "\\App\\Entity\\Ort\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Entity-Ort.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\Ort\u003A\u003AgetPLZ\u0028\u0029",
            "name": "getPLZ",
            "summary": "",
            "url": "classes/App-Entity-Ort.html#method_getPLZ"
        },                {
            "fqsen": "\\App\\Entity\\Ort\u003A\u003AsetPLZ\u0028\u0029",
            "name": "setPLZ",
            "summary": "",
            "url": "classes/App-Entity-Ort.html#method_setPLZ"
        },                {
            "fqsen": "\\App\\Entity\\Ort\u003A\u003AgetOrt\u0028\u0029",
            "name": "getOrt",
            "summary": "",
            "url": "classes/App-Entity-Ort.html#method_getOrt"
        },                {
            "fqsen": "\\App\\Entity\\Ort\u003A\u003AsetOrt\u0028\u0029",
            "name": "setOrt",
            "summary": "",
            "url": "classes/App-Entity-Ort.html#method_setOrt"
        },                {
            "fqsen": "\\App\\Entity\\Ort\u003A\u003AgetRestaurants\u0028\u0029",
            "name": "getRestaurants",
            "summary": "",
            "url": "classes/App-Entity-Ort.html#method_getRestaurants"
        },                {
            "fqsen": "\\App\\Entity\\Ort\u003A\u003AaddRestaurant\u0028\u0029",
            "name": "addRestaurant",
            "summary": "",
            "url": "classes/App-Entity-Ort.html#method_addRestaurant"
        },                {
            "fqsen": "\\App\\Entity\\Ort\u003A\u003AremoveRestaurant\u0028\u0029",
            "name": "removeRestaurant",
            "summary": "",
            "url": "classes/App-Entity-Ort.html#method_removeRestaurant"
        },                {
            "fqsen": "\\App\\Entity\\Ort\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-Ort.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\Ort\u003A\u003A\u0024PLZ",
            "name": "PLZ",
            "summary": "",
            "url": "classes/App-Entity-Ort.html#property_PLZ"
        },                {
            "fqsen": "\\App\\Entity\\Ort\u003A\u003A\u0024Ort",
            "name": "Ort",
            "summary": "",
            "url": "classes/App-Entity-Ort.html#property_Ort"
        },                {
            "fqsen": "\\App\\Entity\\Ort\u003A\u003A\u0024restaurants",
            "name": "restaurants",
            "summary": "",
            "url": "classes/App-Entity-Ort.html#property_restaurants"
        },                {
            "fqsen": "\\App\\Repository\\OrtRepository",
            "name": "OrtRepository",
            "summary": "",
            "url": "classes/App-Repository-OrtRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\OrtRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Repository-OrtRepository.html#method___construct"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\App\\Controller",
            "name": "Controller",
            "summary": "",
            "url": "namespaces/app-controller.html"
        },                {
            "fqsen": "\\App\\Entity",
            "name": "Entity",
            "summary": "",
            "url": "namespaces/app-entity.html"
        },                {
            "fqsen": "\\App",
            "name": "App",
            "summary": "",
            "url": "namespaces/app.html"
        },                {
            "fqsen": "\\App\\Repository",
            "name": "Repository",
            "summary": "",
            "url": "namespaces/app-repository.html"
        }            ]
);
