Search.appendIndex(
    [
                {
            "fqsen": "\\App\\Controller\\CartContoller",
            "name": "CartContoller",
            "summary": "",
            "url": "classes/App-Controller-CartContoller.html"
        },                {
            "fqsen": "\\App\\Controller\\CartContoller\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/App-Controller-CartContoller.html#method_index"
        },                {
            "fqsen": "\\App\\Controller\\HomeController",
            "name": "HomeController",
            "summary": "",
            "url": "classes/App-Controller-HomeController.html"
        },                {
            "fqsen": "\\App\\Controller\\HomeController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Das\u0020ist\u0020ein\u0020Test",
            "url": "classes/App-Controller-HomeController.html#method_index"
        },                {
            "fqsen": "\\App\\Controller\\HomeController\u003A\u003Agerichte\u0028\u0029",
            "name": "gerichte",
            "summary": "",
            "url": "classes/App-Controller-HomeController.html#method_gerichte"
        },                {
            "fqsen": "\\App\\Entity\\Bestellung",
            "name": "Bestellung",
            "summary": "",
            "url": "classes/App-Entity-Bestellung.html"
        },                {
            "fqsen": "\\App\\Entity\\Bestellung\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Entity-Bestellung.html#method___construct"
        },                {
            "fqsen": "\\App\\Entity\\Bestellung\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Entity-Bestellung.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\Bestellung\u003A\u003AgetGastName\u0028\u0029",
            "name": "getGastName",
            "summary": "",
            "url": "classes/App-Entity-Bestellung.html#method_getGastName"
        },                {
            "fqsen": "\\App\\Entity\\Bestellung\u003A\u003AsetGastName\u0028\u0029",
            "name": "setGastName",
            "summary": "",
            "url": "classes/App-Entity-Bestellung.html#method_setGastName"
        },                {
            "fqsen": "\\App\\Entity\\Bestellung\u003A\u003AgetGerichte\u0028\u0029",
            "name": "getGerichte",
            "summary": "",
            "url": "classes/App-Entity-Bestellung.html#method_getGerichte"
        },                {
            "fqsen": "\\App\\Entity\\Bestellung\u003A\u003AaddGerichte\u0028\u0029",
            "name": "addGerichte",
            "summary": "",
            "url": "classes/App-Entity-Bestellung.html#method_addGerichte"
        },                {
            "fqsen": "\\App\\Entity\\Bestellung\u003A\u003AremoveGerichte\u0028\u0029",
            "name": "removeGerichte",
            "summary": "",
            "url": "classes/App-Entity-Bestellung.html#method_removeGerichte"
        },                {
            "fqsen": "\\App\\Entity\\Bestellung\u003A\u003AgetSammelBestellung\u0028\u0029",
            "name": "getSammelBestellung",
            "summary": "",
            "url": "classes/App-Entity-Bestellung.html#method_getSammelBestellung"
        },                {
            "fqsen": "\\App\\Entity\\Bestellung\u003A\u003AsetSammelBestellung\u0028\u0029",
            "name": "setSammelBestellung",
            "summary": "",
            "url": "classes/App-Entity-Bestellung.html#method_setSammelBestellung"
        },                {
            "fqsen": "\\App\\Entity\\Bestellung\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-Bestellung.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\Bestellung\u003A\u003A\u0024GastName",
            "name": "GastName",
            "summary": "",
            "url": "classes/App-Entity-Bestellung.html#property_GastName"
        },                {
            "fqsen": "\\App\\Entity\\Bestellung\u003A\u003A\u0024Gerichte",
            "name": "Gerichte",
            "summary": "",
            "url": "classes/App-Entity-Bestellung.html#property_Gerichte"
        },                {
            "fqsen": "\\App\\Entity\\Bestellung\u003A\u003A\u0024SammelBestellung",
            "name": "SammelBestellung",
            "summary": "",
            "url": "classes/App-Entity-Bestellung.html#property_SammelBestellung"
        },                {
            "fqsen": "\\App\\Entity\\Gericht",
            "name": "Gericht",
            "summary": "",
            "url": "classes/App-Entity-Gericht.html"
        },                {
            "fqsen": "\\App\\Entity\\Gericht\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Entity-Gericht.html#method___construct"
        },                {
            "fqsen": "\\App\\Entity\\Gericht\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Entity-Gericht.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\Gericht\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "",
            "url": "classes/App-Entity-Gericht.html#method_getName"
        },                {
            "fqsen": "\\App\\Entity\\Gericht\u003A\u003AsetName\u0028\u0029",
            "name": "setName",
            "summary": "",
            "url": "classes/App-Entity-Gericht.html#method_setName"
        },                {
            "fqsen": "\\App\\Entity\\Gericht\u003A\u003AgetBeschreibung\u0028\u0029",
            "name": "getBeschreibung",
            "summary": "",
            "url": "classes/App-Entity-Gericht.html#method_getBeschreibung"
        },                {
            "fqsen": "\\App\\Entity\\Gericht\u003A\u003AsetBeschreibung\u0028\u0029",
            "name": "setBeschreibung",
            "summary": "",
            "url": "classes/App-Entity-Gericht.html#method_setBeschreibung"
        },                {
            "fqsen": "\\App\\Entity\\Gericht\u003A\u003AgetRestaurant\u0028\u0029",
            "name": "getRestaurant",
            "summary": "",
            "url": "classes/App-Entity-Gericht.html#method_getRestaurant"
        },                {
            "fqsen": "\\App\\Entity\\Gericht\u003A\u003AsetRestaurant\u0028\u0029",
            "name": "setRestaurant",
            "summary": "",
            "url": "classes/App-Entity-Gericht.html#method_setRestaurant"
        },                {
            "fqsen": "\\App\\Entity\\Gericht\u003A\u003AgetKategories\u0028\u0029",
            "name": "getKategories",
            "summary": "",
            "url": "classes/App-Entity-Gericht.html#method_getKategories"
        },                {
            "fqsen": "\\App\\Entity\\Gericht\u003A\u003AaddKategory\u0028\u0029",
            "name": "addKategory",
            "summary": "",
            "url": "classes/App-Entity-Gericht.html#method_addKategory"
        },                {
            "fqsen": "\\App\\Entity\\Gericht\u003A\u003AremoveKategory\u0028\u0029",
            "name": "removeKategory",
            "summary": "",
            "url": "classes/App-Entity-Gericht.html#method_removeKategory"
        },                {
            "fqsen": "\\App\\Entity\\Gericht\u003A\u003AgetGerichtVariations\u0028\u0029",
            "name": "getGerichtVariations",
            "summary": "",
            "url": "classes/App-Entity-Gericht.html#method_getGerichtVariations"
        },                {
            "fqsen": "\\App\\Entity\\Gericht\u003A\u003AaddGerichtVariation\u0028\u0029",
            "name": "addGerichtVariation",
            "summary": "",
            "url": "classes/App-Entity-Gericht.html#method_addGerichtVariation"
        },                {
            "fqsen": "\\App\\Entity\\Gericht\u003A\u003AremoveGerichtVariation\u0028\u0029",
            "name": "removeGerichtVariation",
            "summary": "",
            "url": "classes/App-Entity-Gericht.html#method_removeGerichtVariation"
        },                {
            "fqsen": "\\App\\Entity\\Gericht\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-Gericht.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\Gericht\u003A\u003A\u0024Name",
            "name": "Name",
            "summary": "",
            "url": "classes/App-Entity-Gericht.html#property_Name"
        },                {
            "fqsen": "\\App\\Entity\\Gericht\u003A\u003A\u0024Beschreibung",
            "name": "Beschreibung",
            "summary": "",
            "url": "classes/App-Entity-Gericht.html#property_Beschreibung"
        },                {
            "fqsen": "\\App\\Entity\\Gericht\u003A\u003A\u0024restaurant",
            "name": "restaurant",
            "summary": "",
            "url": "classes/App-Entity-Gericht.html#property_restaurant"
        },                {
            "fqsen": "\\App\\Entity\\Gericht\u003A\u003A\u0024kategories",
            "name": "kategories",
            "summary": "",
            "url": "classes/App-Entity-Gericht.html#property_kategories"
        },                {
            "fqsen": "\\App\\Entity\\Gericht\u003A\u003A\u0024gerichtVariations",
            "name": "gerichtVariations",
            "summary": "",
            "url": "classes/App-Entity-Gericht.html#property_gerichtVariations"
        },                {
            "fqsen": "\\App\\Entity\\GerichtVariation",
            "name": "GerichtVariation",
            "summary": "",
            "url": "classes/App-Entity-GerichtVariation.html"
        },                {
            "fqsen": "\\App\\Entity\\GerichtVariation\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Entity-GerichtVariation.html#method___construct"
        },                {
            "fqsen": "\\App\\Entity\\GerichtVariation\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Entity-GerichtVariation.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\GerichtVariation\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "",
            "url": "classes/App-Entity-GerichtVariation.html#method_getName"
        },                {
            "fqsen": "\\App\\Entity\\GerichtVariation\u003A\u003AsetName\u0028\u0029",
            "name": "setName",
            "summary": "",
            "url": "classes/App-Entity-GerichtVariation.html#method_setName"
        },                {
            "fqsen": "\\App\\Entity\\GerichtVariation\u003A\u003AgetIsDefault\u0028\u0029",
            "name": "getIsDefault",
            "summary": "",
            "url": "classes/App-Entity-GerichtVariation.html#method_getIsDefault"
        },                {
            "fqsen": "\\App\\Entity\\GerichtVariation\u003A\u003AsetIsDefault\u0028\u0029",
            "name": "setIsDefault",
            "summary": "",
            "url": "classes/App-Entity-GerichtVariation.html#method_setIsDefault"
        },                {
            "fqsen": "\\App\\Entity\\GerichtVariation\u003A\u003AgetPreis\u0028\u0029",
            "name": "getPreis",
            "summary": "",
            "url": "classes/App-Entity-GerichtVariation.html#method_getPreis"
        },                {
            "fqsen": "\\App\\Entity\\GerichtVariation\u003A\u003AsetPreis\u0028\u0029",
            "name": "setPreis",
            "summary": "",
            "url": "classes/App-Entity-GerichtVariation.html#method_setPreis"
        },                {
            "fqsen": "\\App\\Entity\\GerichtVariation\u003A\u003AgetGericht\u0028\u0029",
            "name": "getGericht",
            "summary": "",
            "url": "classes/App-Entity-GerichtVariation.html#method_getGericht"
        },                {
            "fqsen": "\\App\\Entity\\GerichtVariation\u003A\u003AsetGericht\u0028\u0029",
            "name": "setGericht",
            "summary": "",
            "url": "classes/App-Entity-GerichtVariation.html#method_setGericht"
        },                {
            "fqsen": "\\App\\Entity\\GerichtVariation\u003A\u003AgetBestellungen\u0028\u0029",
            "name": "getBestellungen",
            "summary": "",
            "url": "classes/App-Entity-GerichtVariation.html#method_getBestellungen"
        },                {
            "fqsen": "\\App\\Entity\\GerichtVariation\u003A\u003AaddBestellungen\u0028\u0029",
            "name": "addBestellungen",
            "summary": "",
            "url": "classes/App-Entity-GerichtVariation.html#method_addBestellungen"
        },                {
            "fqsen": "\\App\\Entity\\GerichtVariation\u003A\u003AremoveBestellungen\u0028\u0029",
            "name": "removeBestellungen",
            "summary": "",
            "url": "classes/App-Entity-GerichtVariation.html#method_removeBestellungen"
        },                {
            "fqsen": "\\App\\Entity\\GerichtVariation\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-GerichtVariation.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\GerichtVariation\u003A\u003A\u0024Name",
            "name": "Name",
            "summary": "",
            "url": "classes/App-Entity-GerichtVariation.html#property_Name"
        },                {
            "fqsen": "\\App\\Entity\\GerichtVariation\u003A\u003A\u0024isDefault",
            "name": "isDefault",
            "summary": "",
            "url": "classes/App-Entity-GerichtVariation.html#property_isDefault"
        },                {
            "fqsen": "\\App\\Entity\\GerichtVariation\u003A\u003A\u0024Preis",
            "name": "Preis",
            "summary": "",
            "url": "classes/App-Entity-GerichtVariation.html#property_Preis"
        },                {
            "fqsen": "\\App\\Entity\\GerichtVariation\u003A\u003A\u0024Gericht",
            "name": "Gericht",
            "summary": "",
            "url": "classes/App-Entity-GerichtVariation.html#property_Gericht"
        },                {
            "fqsen": "\\App\\Entity\\GerichtVariation\u003A\u003A\u0024bestellungen",
            "name": "bestellungen",
            "summary": "",
            "url": "classes/App-Entity-GerichtVariation.html#property_bestellungen"
        },                {
            "fqsen": "\\App\\Entity\\Kategorie",
            "name": "Kategorie",
            "summary": "",
            "url": "classes/App-Entity-Kategorie.html"
        },                {
            "fqsen": "\\App\\Entity\\Kategorie\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Entity-Kategorie.html#method___construct"
        },                {
            "fqsen": "\\App\\Entity\\Kategorie\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Entity-Kategorie.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\Kategorie\u003A\u003AgetBezeichner\u0028\u0029",
            "name": "getBezeichner",
            "summary": "",
            "url": "classes/App-Entity-Kategorie.html#method_getBezeichner"
        },                {
            "fqsen": "\\App\\Entity\\Kategorie\u003A\u003AsetBezeichner\u0028\u0029",
            "name": "setBezeichner",
            "summary": "",
            "url": "classes/App-Entity-Kategorie.html#method_setBezeichner"
        },                {
            "fqsen": "\\App\\Entity\\Kategorie\u003A\u003AgetRestaurant\u0028\u0029",
            "name": "getRestaurant",
            "summary": "",
            "url": "classes/App-Entity-Kategorie.html#method_getRestaurant"
        },                {
            "fqsen": "\\App\\Entity\\Kategorie\u003A\u003AsetRestaurant\u0028\u0029",
            "name": "setRestaurant",
            "summary": "",
            "url": "classes/App-Entity-Kategorie.html#method_setRestaurant"
        },                {
            "fqsen": "\\App\\Entity\\Kategorie\u003A\u003AgetGerichte\u0028\u0029",
            "name": "getGerichte",
            "summary": "",
            "url": "classes/App-Entity-Kategorie.html#method_getGerichte"
        },                {
            "fqsen": "\\App\\Entity\\Kategorie\u003A\u003AaddGerichte\u0028\u0029",
            "name": "addGerichte",
            "summary": "",
            "url": "classes/App-Entity-Kategorie.html#method_addGerichte"
        },                {
            "fqsen": "\\App\\Entity\\Kategorie\u003A\u003AremoveGerichte\u0028\u0029",
            "name": "removeGerichte",
            "summary": "",
            "url": "classes/App-Entity-Kategorie.html#method_removeGerichte"
        },                {
            "fqsen": "\\App\\Entity\\Kategorie\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-Kategorie.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\Kategorie\u003A\u003A\u0024Bezeichner",
            "name": "Bezeichner",
            "summary": "",
            "url": "classes/App-Entity-Kategorie.html#property_Bezeichner"
        },                {
            "fqsen": "\\App\\Entity\\Kategorie\u003A\u003A\u0024Restaurant",
            "name": "Restaurant",
            "summary": "",
            "url": "classes/App-Entity-Kategorie.html#property_Restaurant"
        },                {
            "fqsen": "\\App\\Entity\\Kategorie\u003A\u003A\u0024Gerichte",
            "name": "Gerichte",
            "summary": "",
            "url": "classes/App-Entity-Kategorie.html#property_Gerichte"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant",
            "name": "Restaurant",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#method___construct"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#method_getName"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003AsetName\u0028\u0029",
            "name": "setName",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#method_setName"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003AgetTelefonNr\u0028\u0029",
            "name": "getTelefonNr",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#method_getTelefonNr"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003AsetTelefonNr\u0028\u0029",
            "name": "setTelefonNr",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#method_setTelefonNr"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003AgetMobil\u0028\u0029",
            "name": "getMobil",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#method_getMobil"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003AsetMobil\u0028\u0029",
            "name": "setMobil",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#method_setMobil"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003AgetStra\u00DFe\u0028\u0029",
            "name": "getStra\u00DFe",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#method_getStra%C3%9Fe"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003AsetStra\u00DFe\u0028\u0029",
            "name": "setStra\u00DFe",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#method_setStra%C3%9Fe"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003AgetHausNr\u0028\u0029",
            "name": "getHausNr",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#method_getHausNr"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003AsetHausNr\u0028\u0029",
            "name": "setHausNr",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#method_setHausNr"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003AgetGerichte\u0028\u0029",
            "name": "getGerichte",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#method_getGerichte"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003AaddGerichte\u0028\u0029",
            "name": "addGerichte",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#method_addGerichte"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003AremoveGerichte\u0028\u0029",
            "name": "removeGerichte",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#method_removeGerichte"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003AgetKategories\u0028\u0029",
            "name": "getKategories",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#method_getKategories"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003AaddKategory\u0028\u0029",
            "name": "addKategory",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#method_addKategory"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003AremoveKategory\u0028\u0029",
            "name": "removeKategory",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#method_removeKategory"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003A\u0024Name",
            "name": "Name",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#property_Name"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003A\u0024TelefonNr",
            "name": "TelefonNr",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#property_TelefonNr"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003A\u0024Mobil",
            "name": "Mobil",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#property_Mobil"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003A\u0024Stra\u00DFe",
            "name": "Stra\u00DFe",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#property_Stra%C3%9Fe"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003A\u0024HausNr",
            "name": "HausNr",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#property_HausNr"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003A\u0024Gerichte",
            "name": "Gerichte",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#property_Gerichte"
        },                {
            "fqsen": "\\App\\Entity\\Restaurant\u003A\u003A\u0024kategories",
            "name": "kategories",
            "summary": "",
            "url": "classes/App-Entity-Restaurant.html#property_kategories"
        },                {
            "fqsen": "\\App\\Entity\\SammelBestellung",
            "name": "SammelBestellung",
            "summary": "",
            "url": "classes/App-Entity-SammelBestellung.html"
        },                {
            "fqsen": "\\App\\Entity\\SammelBestellung\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Entity-SammelBestellung.html#method___construct"
        },                {
            "fqsen": "\\App\\Entity\\SammelBestellung\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Entity-SammelBestellung.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\SammelBestellung\u003A\u003AgetPublicID\u0028\u0029",
            "name": "getPublicID",
            "summary": "",
            "url": "classes/App-Entity-SammelBestellung.html#method_getPublicID"
        },                {
            "fqsen": "\\App\\Entity\\SammelBestellung\u003A\u003AsetPublicID\u0028\u0029",
            "name": "setPublicID",
            "summary": "",
            "url": "classes/App-Entity-SammelBestellung.html#method_setPublicID"
        },                {
            "fqsen": "\\App\\Entity\\SammelBestellung\u003A\u003AgetAdminID\u0028\u0029",
            "name": "getAdminID",
            "summary": "",
            "url": "classes/App-Entity-SammelBestellung.html#method_getAdminID"
        },                {
            "fqsen": "\\App\\Entity\\SammelBestellung\u003A\u003AsetAdminID\u0028\u0029",
            "name": "setAdminID",
            "summary": "",
            "url": "classes/App-Entity-SammelBestellung.html#method_setAdminID"
        },                {
            "fqsen": "\\App\\Entity\\SammelBestellung\u003A\u003AgetBestellungs\u0028\u0029",
            "name": "getBestellungs",
            "summary": "",
            "url": "classes/App-Entity-SammelBestellung.html#method_getBestellungs"
        },                {
            "fqsen": "\\App\\Entity\\SammelBestellung\u003A\u003AaddBestellung\u0028\u0029",
            "name": "addBestellung",
            "summary": "",
            "url": "classes/App-Entity-SammelBestellung.html#method_addBestellung"
        },                {
            "fqsen": "\\App\\Entity\\SammelBestellung\u003A\u003AremoveBestellung\u0028\u0029",
            "name": "removeBestellung",
            "summary": "",
            "url": "classes/App-Entity-SammelBestellung.html#method_removeBestellung"
        },                {
            "fqsen": "\\App\\Entity\\SammelBestellung\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-SammelBestellung.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\SammelBestellung\u003A\u003A\u0024PublicID",
            "name": "PublicID",
            "summary": "",
            "url": "classes/App-Entity-SammelBestellung.html#property_PublicID"
        },                {
            "fqsen": "\\App\\Entity\\SammelBestellung\u003A\u003A\u0024AdminID",
            "name": "AdminID",
            "summary": "",
            "url": "classes/App-Entity-SammelBestellung.html#property_AdminID"
        },                {
            "fqsen": "\\App\\Entity\\SammelBestellung\u003A\u003A\u0024bestellungs",
            "name": "bestellungs",
            "summary": "",
            "url": "classes/App-Entity-SammelBestellung.html#property_bestellungs"
        },                {
            "fqsen": "\\App\\Kernel",
            "name": "Kernel",
            "summary": "",
            "url": "classes/App-Kernel.html"
        },                {
            "fqsen": "\\App\\Kernel\u003A\u003AconfigureContainer\u0028\u0029",
            "name": "configureContainer",
            "summary": "",
            "url": "classes/App-Kernel.html#method_configureContainer"
        },                {
            "fqsen": "\\App\\Kernel\u003A\u003AconfigureRoutes\u0028\u0029",
            "name": "configureRoutes",
            "summary": "",
            "url": "classes/App-Kernel.html#method_configureRoutes"
        },                {
            "fqsen": "\\App\\Repository\\BestellungRepository",
            "name": "BestellungRepository",
            "summary": "",
            "url": "classes/App-Repository-BestellungRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\BestellungRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Repository-BestellungRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\GerichtRepository",
            "name": "GerichtRepository",
            "summary": "",
            "url": "classes/App-Repository-GerichtRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\GerichtRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Repository-GerichtRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\GerichtVariationRepository",
            "name": "GerichtVariationRepository",
            "summary": "",
            "url": "classes/App-Repository-GerichtVariationRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\GerichtVariationRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Repository-GerichtVariationRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\KategorieRepository",
            "name": "KategorieRepository",
            "summary": "",
            "url": "classes/App-Repository-KategorieRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\KategorieRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Repository-KategorieRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\RestaurantRepository",
            "name": "RestaurantRepository",
            "summary": "",
            "url": "classes/App-Repository-RestaurantRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\RestaurantRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Repository-RestaurantRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\RestaurantRepository\u003A\u003AgibtAlleRestaurantsHer\u0028\u0029",
            "name": "gibtAlleRestaurantsHer",
            "summary": "",
            "url": "classes/App-Repository-RestaurantRepository.html#method_gibtAlleRestaurantsHer"
        },                {
            "fqsen": "\\App\\Repository\\SammelBestellungRepository",
            "name": "SammelBestellungRepository",
            "summary": "",
            "url": "classes/App-Repository-SammelBestellungRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\SammelBestellungRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Repository-SammelBestellungRepository.html#method___construct"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\App\\Controller",
            "name": "Controller",
            "summary": "",
            "url": "namespaces/app-controller.html"
        },                {
            "fqsen": "\\App\\Entity",
            "name": "Entity",
            "summary": "",
            "url": "namespaces/app-entity.html"
        },                {
            "fqsen": "\\App",
            "name": "App",
            "summary": "",
            "url": "namespaces/app.html"
        },                {
            "fqsen": "\\App\\Repository",
            "name": "Repository",
            "summary": "",
            "url": "namespaces/app-repository.html"
        }            ]
);
